<template>
  <div class="about pa-6">
    <h1>About Vuetify Todo</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nulla libero, faucibus vitae ligula ut, ultrices convallis neque. Nunc eu elit sapien. Sed ut lacus massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam non leo feugiat, porttitor mi id, dictum sapien. Nulla suscipit rhoncus felis. Phasellus finibus mauris ac magna aliquam auctor. Cras mollis eros ac rutrum rhoncus. Proin facilisis, magna dictum consequat pharetra, purus arcu elementum ligula, ut pharetra nisl dui et lectus. Nunc tempus urna ut lacinia scelerisque. Nam vitae pellentesque neque, id accumsan lacus. Aliquam consequat nulla quis lacus facilisis, quis faucibus tortor efficitur. Phasellus convallis ipsum in odio porttitor consequat.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nulla libero, faucibus vitae ligula ut, ultrices convallis neque. Nunc eu elit sapien. Sed ut lacus massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam non leo feugiat, porttitor mi id, dictum sapien. Nulla suscipit rhoncus felis. Phasellus finibus mauris ac magna aliquam auctor. Cras mollis eros ac rutrum rhoncus. Proin facilisis, magna dictum consequat pharetra, purus arcu elementum ligula, ut pharetra nisl dui et lectus. Nunc tempus urna ut lacinia scelerisque. Nam vitae pellentesque neque, id accumsan lacus. Aliquam consequat nulla quis lacus facilisis, quis faucibus tortor efficitur. Phasellus convallis ipsum in odio porttitor consequat.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nulla libero, faucibus vitae ligula ut, ultrices convallis neque. Nunc eu elit sapien. Sed ut lacus massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam non leo feugiat, porttitor mi id, dictum sapien. Nulla suscipit rhoncus felis. Phasellus finibus mauris ac magna aliquam auctor. Cras mollis eros ac rutrum rhoncus. Proin facilisis, magna dictum consequat pharetra, purus arcu elementum ligula, ut pharetra nisl dui et lectus. Nunc tempus urna ut lacinia scelerisque. Nam vitae pellentesque neque, id accumsan lacus. Aliquam consequat nulla quis lacus facilisis, quis faucibus tortor efficitur. Phasellus convallis ipsum in odio porttitor consequat.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nulla libero, faucibus vitae ligula ut, ultrices convallis neque. Nunc eu elit sapien. Sed ut lacus massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam non leo feugiat, porttitor mi id, dictum sapien. Nulla suscipit rhoncus felis. Phasellus finibus mauris ac magna aliquam auctor. Cras mollis eros ac rutrum rhoncus. Proin facilisis, magna dictum consequat pharetra, purus arcu elementum ligula, ut pharetra nisl dui et lectus. Nunc tempus urna ut lacinia scelerisque. Nam vitae pellentesque neque, id accumsan lacus. Aliquam consequat nulla quis lacus facilisis, quis faucibus tortor efficitur. Phasellus convallis ipsum in odio porttitor consequat.</p>
  </div>
</template>
